# This is a Docker Compose configuration
# intended for development purposes only

version: '3'

volumes:
  db: {}

networks:
  game: {}

services:
  db:
    container_name: game-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: game
      MYSQL_USER: game_user
      MYSQL_PASSWORD: qazxsw
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
    networks:
      - game

  app:
    container_name: game-app
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    restart: unless-stopped
    environment:
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: game
      DB_USERNAME: game_user
      DB_PASSWORD: qazxsw
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - game
    entrypoint: ./dockerfiles/entrypoint.app.sh

  nginx:
    image: nginx:stable-alpine
    container_name: game-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www/html
      - ./dockerfiles/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
      - db
    networks:
      - game
  node:
    image: node:18.4.0
    container_name: game-node
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - game
    entrypoint: ./dockerfiles/entrypoint.node.sh